kibot:
  version: 1
  imported_global_has_less_priority: true

preflight:
  erc: false
  drc: false
  set_text_variables:
    # The revision will be the short git hash
    # We use ${git_hash} for the REV field in the worksheet (frame)
    - name: 'git_hash'
      command: 'git log -1 --format="%h" $KIBOT_PCB_NAME'
      before: 'Git:'
    # Coherent date and time for the schematic and PCB
    # This will be the time stamp of the files generation, not the commit times
    # We use `${date}` for the time field in the worksheet (frame)
    - name: 'date'
      command: 'date --iso-8601=minutes'

variants:
  - name: 'PrimaryNodeESP32S3'
    comment: 'Primary node with ESP32-S3'
    type: kibom
    file_id: _PrimaryNodeESP32S3
    variant: PrimaryNodeESP32S3
  - name: 'PrimaryNodeESP32Devkit'
    comment: 'Primary node with ESP32-DevKit'
    type: kibom
    file_id: _PrimaryNodeESP32Devkit
    variant: PrimaryNodeESP32Devkit
  - name: 'SubNode'
    comment: 'Full board'
    type: kibom
    file_id: _SubNode
    variant: SubNode

import:
  - file: JLCPCB_stencil_with_THT
  - file: PCBWay_stencil
  - file: Elecrow_stencil
  - file: FusionPCB_stencil
  - file: P-Ban_stencil
