kibot:
  version: 1
  imported_global_has_less_priority: true

global:
  field_lcsc_part: 'LCSC#'

preflight:
  erc: false
  drc: false
  set_text_variables:
    # The revision will be the short git hash
    # We use ${git_hash} for the REV field in the worksheet (frame)
    - name: 'git_hash'
      command: 'git log -1 --format="%h" $KIBOT_PCB_NAME'
      before: 'Git:'
    # Coherent date and time for the schematic and PCB
    # This will be the time stamp of the files generation, not the commit times
    # We use `${date}` for the time field in the worksheet (frame)
    - name: 'date'
      command: 'date --iso-8601=minutes'

import:
  - file: FabGeneric.kitbot.yaml
  - file: FabJLCPCB.kibot.yaml
  - file: PCBWay_stencil
  - file: Elecrow_stencil
  - file: FusionPCB_stencil
  - file: P-Ban_stencil
