name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 

jobs:
  Build_SX1509:
    call-workflow-passing-data:
      uses: ./.github/workflows/template_kitbot_build.yml
      with:
        pcb-dir-prefix: SX1509

  Build_PCA9685:
    call-workflow-passing-data:
      uses: ./.github/workflows/template_kitbot_build.yml
      with:
        pcb-dir-prefix: PCA9685
