name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
#    paths:
#      - 'kibot/**.*'
#      - 'pcb_*/**.*' 

jobs:
  call-workflow-passing-data:
    strategy:
      matrix:
        target: [SX1509, PCA9685]
    uses: ./.github/workflows/template_kitbot_build.yml
    with:
      pcb-dir-prefix: ${{ matrix.target }}
