name: KitBot - Last PCB check

on:
  push:
    branches: 
      - main
    paths:
      - 'kibot/**.*'
      - 'pcb_*/**.*' 
  pull_request:
    branches: 
      - main
    paths:
      - 'kibot/**.*'
      - 'pcb_*/**.*' 

jobs:
  ERC_SX1509:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        schema: 'pcb_SX1509/project.kicad_sch'
        board: 'pcb_SX1509/project.kicad_pcb'
        verbose: 0
        dir: Generated
        skip: drc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_SX1509_Output
        path: Generated
        retention-days: 1

  ERC_PCA9685:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        schema: 'pcb_PCA9685/project.kicad_sch'
        board: 'pcb_PCA9685/project.kicad_pcb'
        verbose: 0
        dir: Generated
        skip: drc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: ERC_PCA9685_Output
        path: Generated
        retention-days: 1

  DRC_SX1509:
    runs-on: ubuntu-latest
    needs: ERC_SX1509
    steps:
    - uses: actions/checkout@v4
    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        schema: 'pcb_SX1509/project.kicad_sch'
        board: 'pcb_SX1509/project.kicad_pcb'
        verbose: 0
        dir: Generated
        skip: erc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_SX1509_Output
        path: Generated
        retention-days: 1

  DRC_PCA9685:
    runs-on: ubuntu-latest
    needs: ERC_PCA9685
    steps:
    - uses: actions/checkout@v4
    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        schema: 'pcb_PCA9685/project.kicad_sch'
        board: 'pcb_PCA9685/project.kicad_pcb'
        verbose: 0
        dir: Generated
        skip: erc
        targets: __NONE__
    - name: Retrieve results
      uses: actions/upload-artifact@v4
      with:
        name: DRC_PCA9685_Output
        path: Generated
        retention-days: 1

  Fabrication_SX1509:
    name: "Build PCB files"
    runs-on: ubuntu-latest
    needs: [ERC_SX1509, DRC_SX1509]
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        dir: pcb_SX1509
        schema: 'pcb_SX1509/project.kicad_sch'
        board: 'pcb_SX1509/project.kicad_pcb'
        verbose: 0
        skip: erc,drc
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/production.kibot.yaml
        dir: pcb_SX1509/production
        schema: 'pcb_SX1509/project.kicad_sch'
        board: 'pcb_SX1509/project.kicad_pcb'
        verbose: 0
        skip: erc,drc
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: fabrication_SX1509
        path: pcb_SX1509
        retention-days: 1

  Fabrication_PCA9685:
    name: "Build PCB files"
    runs-on: ubuntu-latest
    needs: [ERC_PCA9685, DRC_PCA9685]
    steps:
    - uses: actions/checkout@v4
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/base.kibot.yaml
        dir: pcb_PCA9685
        schema: 'pcb_PCA9685/project.kicad_sch'
        board: 'pcb_PCA9685/project.kicad_pcb'
        verbose: 0
        skip: erc,drc
    - uses: INTI-CMNB/KiBot@v2_k8
      with:
        config: kibot/production.kibot.yaml
        dir: pcb_PCA9685/production
        schema: 'pcb_PCA9685/project.kicad_sch'
        board: 'pcb_PCA9685/project.kicad_pcb'
        verbose: 0
        skip: erc,drc
    - name: upload results
      uses: actions/upload-artifact@v4
      with:
        name: fabrication_PCA9685
        path: pcb_PCA9685
        retention-days: 1

